# This workflow automates the process of identifying potential security vulnerabilities using Snyk. 
# Dependency vulnerability scans will be run on a weekly schedule, but can also be triggered manually.
name: Snyk Vulnerability Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * 1'
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4
        with:
          ref: 'main'

      - name: Run Snyk To Check For Vulnerabilities
        uses: snyk/actions/gradle-jdk11@8349f9043a8b7f0f3ee8885bf28f0b388d2446e8 # pin@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --all-sub-projects --org=java-agent --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'
